name: Changesets - Release

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    concurrency:
      group: changesets-release
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          scope: '@dexto'
      # Rely on setup-node + NODE_AUTH_TOKEN for auth; avoid writing .npmrc manually
      - name: Verify npm auth & registry
        run: |
          echo "NPM_CONFIG_USERCONFIG=${NPM_CONFIG_USERCONFIG:-$HOME/.npmrc}"
          echo "--- .npmrc (sanitized) ---"
          if [ -f "${NPM_CONFIG_USERCONFIG:-$HOME/.npmrc}" ]; then
            sed -E 's/(^.*:_authToken=).*/\1*** (masked)/' "${NPM_CONFIG_USERCONFIG:-$HOME/.npmrc}" | grep -E 'registry|always-auth|@dexto' || true
          else
            echo "No .npmrc found at expected path"
          fi
          echo "npm version: $(npm --version)"
          echo "pnpm version: $(pnpm --version)"
          echo "registry=$(npm config get registry)"
          echo "whoami=$(npm whoami || echo unknown)"
          npm view dexto maintainers --json || true
      - run: pnpm install --frozen-lockfile
      - name: Version / Publish with Changesets
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          version: pnpm run changeset:version
          publish: pnpm run changeset:publish
